name: Sync Supabase DBs

on:
  workflow_dispatch: # run manually from GitHub Actions UI
  schedule:
    - cron: "0 * * * *" # every hour (adjust as needed)

jobs:
  sync-databases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ruby & pgsync
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install pgsync

      - name: Run DB Sync
        env:
          DATABASE_URL_FROM: postgresql://postgres.aglpkgpajcgjdlfunwyr:${{ secrets.SOURCE_DB_PASSWORD }}@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
          DATABASE_URL_TO: postgresql://postgres.ritrltdfyhulykpxbefe:${{ secrets.TARGET_DB_PASSWORD }}@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
        run: |
          pgsync --in-batches --overwrite --from "$DATABASE_URL_FROM" --to "$DATABASE_URL_TO"
